# Generated by Django 2.1.3 on 2018-11-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181117_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='tax_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
