# Generated by Django 2.1.3 on 2018-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181117_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='tax_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
